[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
# ------------------------------------                                    
# colorscheme tender setting                                    
# ------------------------------------
[[plugins]]                                                                                                                                                                                                                                             
repo = 'jacoborus/tender.vim'                                    
hook_add = '''                                              
    colorscheme tender                                      
    set background=dark                                     
    syntax on                                               
    set t_Co=256                                            
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1                                    
'''
# ------------------------------------                                    
# Git vim-fugitive                                     
# ------------------------------------                                    
[[plugins]]                                    
repo = 'tpope/vim-fugitive'
hook_add = '''                                    
    nnoremap <silent> gs :Gstatus<CR><C-w>T                                    
    nnoremap <silent> gps :Gpush<CR>                                    
    nnoremap <silent> gpl :Gpull<CR>                                    
'''    
[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'cohama/lexima.vim'
